# pull official base image
FROM node:18-alpine as builder
# set working directory
WORKDIR /app
COPY package.json .

RUN npm install 
# add app
COPY . .

RUN npm run build  

# install app dependencies
FROM nginx:alpine

COPY  --from=builder app/build /usr/share/ngxinx/html