version: '3'
services:
   # wip reverse proxy  
  reverse-proxy:
    container_name: proxy-c
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  #app container ok  
  web:
    container_name: web
    image : web-react-i
    build:
      context: .
    ports:
      - 8000:80

    